-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 03-Abr-2017 às 22:51
-- Versão do servidor: 10.1.19-MariaDB
-- PHP Version: 5.5.38

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `comicsnews`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `noticia`
--

CREATE TABLE `noticia` (
  `ID` int(11) NOT NULL,
  `titulo` varchar(100) NOT NULL,
  `descricao` text NOT NULL,
  `img` varchar(100) NOT NULL,
  `data` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `autor` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Extraindo dados da tabela `noticia`
--

INSERT INTO `noticia` (`ID`, `titulo`, `descricao`, `img`, `data`, `autor`) VALUES
(22, 'Confira tudo o que sai da Netflix nesta semana', 'Normalmente, o nÃºmero de programas que sai da Netflix a cada semana supera em muito o nÃºmero de programas que entram. Nessa semana, porÃ©m, nÃ£o Ã© o caso: apenas trÃªs programas saem do serviÃ§o, talvez para compensar o expurgo de fim de mÃªs da semana passada. Esses trÃªs incluem o aterrorizante suspense \\"Wolf Creek\\" e \\"Howl\\", o filme biogrÃ¡fico do poeta beat Allen Ginsberg. Confira:\r\n\r\n05/04\r\n\r\nWolf Creek - Viagem ao Inferno\r\n\r\nParaÃ­so\r\n\r\n \r\n\r\n06/04\r\n\r\nHowl', 'd173d955a26b07338bc1746f0fc6f6f0.jpg', '2017-04-03 18:38:19', 'GUSTAVO SUMARES'),
(23, 'Imagem mostra como pode ser o novo Moto X', 'Uma imagem divulgada nesta segunda-feira, 03, mostra que a Lenovo pode trazer de volta a linha Moto X. O site Droidholic, especialista no sistema operacional do Google, divulgou o que parece ser uma renderizaÃ§Ã£o do aparelho.\r\n\r\nMais uma vez, as especificaÃ§Ãµes foram divulgadas, o que pode confirmar um rumor que surgiu hÃ¡ alguns dias. O aparelho deve ter processador Snapdragon 625, versÃµes de 32 Gb e 64 GB de armazenamento, 3 GB e 4 GB de RAM. A cÃ¢mera traseira deve ter 13 megapixels.', '2d95b760f268b03c51c8b40f840bb543.jpg', '2017-04-03 19:04:36', 'REDAÃ‡ÃƒO OLHAR DIGITAL'),
(24, 'Vaza lista de jogos que terÃ£o performance melhorada no Project Scorpio', 'Nesta semana, os rumores sobre a prÃ³xima versÃ£o do Xbox One, chamada por enquanto de Project Scorpio, comeÃ§aram a esquentar. Ao que tudo indica, a Microsoft deve liberar mais detalhes sobre o console nas prÃ³ximas semanas, incluindo os games que vÃ£o tirar proveito do hardware.\r\n\r\nO site Windows Central divulgou alguns dos tÃ­tulos que terÃ£o performance melhorada graÃ§as ao novo Xbox. A princÃ­pio, \\"Forza Motorsport 7\\", \\"Red Dead Redemption 2\\" e \\"Star Wars: Battlefront 2\\" serÃ£o os destaques na campanha de divulgaÃ§Ã£o do Scorpio.\r\n\r\nNesta semana, os rumores sobre a prÃ³xima versÃ£o do Xbox One, chamada por enquanto de Project Scorpio, comeÃ§aram a esquentar. Ao que tudo indica, a Microsoft deve liberar mais detalhes sobre o console nas prÃ³ximas semanas, incluindo os games que vÃ£o tirar proveito do hardware.\r\n\r\nO site Windows Central divulgou alguns dos tÃ­tulos que terÃ£o performance melhorada graÃ§as ao novo Xbox. A princÃ­pio, \\"Forza Motorsport 7\\", \\"Red Dead Redemption 2\\" e \\"Star Wars: Battlefront 2\\" serÃ£o os destaques na campanha de divulgaÃ§Ã£o do Scorpio.', 'c43f3fff819d6bbc5785f7906ecdbd5a.jpg', '2017-04-03 19:06:05', 'LUCAS CARVALHO'),
(25, 'Mais da metade dos jogadores de PC usam Windows 10, revela Steam', 'A plataforma e loja virtual de games para PC Steam revelou nesta segunda-feira, 3, a nova ediÃ§Ã£o de sua tradicional pesquisa mensal de hardware e software. A novidade Ã© que o Windows 10 Ã© agora o sistema operacional usado por mais da metade dos jogadores de PC.\r\n\r\nSegundo o Steam, o Windows 10 estÃ¡ instalado em 50,15% de todos os computadores cadastrados na plataforma. Em relaÃ§Ã£o ao mÃªs passado, o aumento foi de pouco mais de 2%. AlÃ©m disso, a pesquisa mostra outras especificaÃ§Ãµes populares entre os \\"PC gamers\\".\r\n\r\nPor exemplo: pouco mais de 35% dos jogadores usam mÃ¡quinas com 8 GB de RAM, segundo a pesquisa. AlÃ©m disso, 61% usam placas de vÃ­deo da Nvidia; 79% usam CPUs da Intel; e, dentre os que tÃªm algum tipo de visor de realidade virtual, o modelo mais popular Ã© o HTC Vive (60%).\r\n\r\nOutra especificaÃ§Ã£o popular Ã© a resoluÃ§Ã£o do monitor: 45% usam telas de 1.920 por 1.080 pixels, e 32% usam discos rÃ­gidos de 1 TB ou mais. A maioria (20%) tambÃ©m usa CPUs com velocidades entre 2,3 GHz e 2,69 GHz, quatro nÃºcleos (49%) e GPUs de 1 GB (32%).\r\n\r\nO Steam divulga essa pesquisa mensalmente e diz que a participaÃ§Ã£o dos usuÃ¡rios Ã© opcional e anÃ´nima. O nÃºmero total de mÃ¡quinas avaliadas nÃ£o foi revelado.', '48672aeeb1461fdb11bab53150c537d0.jpg', '2017-04-03 19:09:20', 'LUCAS CARVALHO'),
(26, 'Dados mostram que o streaming nÃ£o estÃ¡ matando a indÃºstria da mÃºsica', 'Ao contrÃ¡rio do que muita gente acredita, o streaming nÃ£o estÃ¡ matando a indÃºstria da mÃºsica. Dados divulgados pela Recording Industry Association of America (RIAA) mostram que o ano passado foi o melhor para o setor desde 2009. As receitas chegaram a US$ 7,7 bilhÃµes. E 51% desse valor vÃªm dos serviÃ§os de streaming.\r\n\r\nO valor nÃ£o vem sÃ³ de anunciantes, que exibem suas propagandas em versÃµes gratuitas de apps como o Spotify e o Deezer. Muita gente jÃ¡ assina esse tipo de serviÃ§o. De acordo com a RIAA, nos Estados Unidos o nÃºmero passou de 10,8 milhÃµes em 2015 para 22,8 milhÃµes em 2016.\r\n\r\nNem todas as notÃ­cias sÃ£o boas. Apesar de se recuperar em relaÃ§Ã£o aos Ãºltimos anos, a indÃºstria musical fatura apenas metade do que faturava em 1999. A receita de downloads digitais de serviÃ§os como o iTunes tambÃ©m caiu, passando de US$ 2,8 bilhÃµes para US$ 1,8 bilhÃ£o em um ano. As vendas fÃ­sicas seguem em queda, com diminuiÃ§Ã£o de 16% em apenas um ano.', 'a5972e6cb1af70a57f3617e90ff65047.jpg', '2017-04-03 19:16:32', 'GUSTAVO SUMARES'),
(27, 'Criador do Oculus Rift deixa o Facebook', 'Palmer Luckey, criador do Oculus Rift, nÃ£o faz mais parte da Oculus VR nem do Facebook, que adquiriu a empresa em 2014 por US$ 2 bilhÃµes. NÃ£o foi divulgado o motivo da separaÃ§Ã£o, mas o fato nÃ£o chega a ser uma surpresa.\r\n\r\nVisto como uma das figuras mais proeminentes na alavancagem da tecnologia da realidade virtual e bilionÃ¡rio com apenas 24 anos, Luckey comeÃ§ou a deixar de aparecer em eventos pÃºblicos da Oculus e atÃ© mesmo deixou de ser mencionado quando o assunto era realidade virtual no Facebook.\r\n\r\nO boicote nunca foi (nem serÃ¡) oficialmente confirmado, mas o fato Ã© que Luckey passou a perder espaÃ§o depois que foi confirmado que ele financiou um grupo de pessoas que criavam memes que beiravam o mau gosto a favor de Donald Trump e contra Hillary Clinton durante a campanha para a PresidÃªncia dos Estados Unidos.\r\n\r\nQuando o fato foi revelado, vÃ¡rias empresas que desenvolviam jogos compatÃ­veis com o Oculus Rift acabaram anunciando o cancelamento do suporte ao visor de realidade virtual como forma de boicote. Isso fez com que a posiÃ§Ã£o de Luckey no Facebook e na Oculus ficasse bastante desconfortÃ¡vel.\r\n\r\nNo entanto, Palmer Luckey parece ter deixado a Oculus sem grandes ressentimentos, segundo o comunicado da empresa repassado ao site UploadVR. â€œPalmer farÃ¡ falta. O lado de Palmer vai muito alÃ©m da Oculus. Seu espÃ­rito inventivo ajudou a alavancar a revoluÃ§Ã£o da realidade virtual moderna e ajudou a construir uma indÃºstria. Somos gratos por tudo que ele fez pela Oculus e pelo VR e desejamos a ele o melhorâ€, disse um representante.', '81f748355869839dde1d5745e51c8e8f.jpg', '2017-04-03 19:17:16', 'RENATO SANTINO'),
(28, 'Uber permitirÃ¡ alterar seu local de partida apÃ³s solicitar um carro', 'O processo de solicitar uma viagem com a Uber tem se mantido quase inalterado pelos Ãºltimos anos: vocÃª seleciona seu endereÃ§o de partida, posiciona uma agulha no mapa para marcar onde vocÃª estÃ¡, determina o endereÃ§o final e espera o carro chegar.\r\n\r\nAcontece que atÃ© hoje nunca foi possÃ­vel alterar o local de partida depois que um motorista Ã© solicitado. VocÃª sÃ³ pode apontar no mapa onde vocÃª estÃ¡ antes que o carro comece a te procurar, e nÃ£o depois. Isso, porÃ©m, estÃ¡ prestes a mudar.\r\n\r\nA Uber comeÃ§ou a testar uma novidade no seu aplicativo nesta semana, a princÃ­pio apenas para usuÃ¡rios do Reino Unido, Estados Unidos e CanadÃ¡, segundo o site Engadget. Passageiros desses paÃ­ses agora podem alterar sua localizaÃ§Ã£o no mapa mesmo depois de solicitar uma corrida, enquanto o motorista nÃ£o chega.\r\n\r\nAssim, caso haja um imprevisto ou mudanÃ§a de planos, vocÃª nÃ£o precisarÃ¡ mais ligar para o motorista e explicar verbalmente onde ele pode te encontrar. Basta que o usuÃ¡rio toque num botÃ£o \\"Editar\\" e reposicione a agulha no mapa - desde que o novo local de partida seja dentro de uma regiÃ£o prÃ³xima Ã  do primeiro local.\r\n\r\nA Uber nÃ£o disse quando a novidade vai deixar Reino Unido, EUA e CanadÃ¡, mas Ã© provÃ¡vel que outros paÃ­ses (incluindo o Brasil) recebam a atualizaÃ§Ã£o nos prÃ³ximos meses.', '77eeb15faeeb7402e7dbc0f49738a383.jpg', '2017-04-03 19:18:59', 'LUCAS CARVALHO'),
(29, 'Batman: Arkham VR Ã© confirmado para HTC Vive e Oculus', 'NÃ£o precisa ficar triste sÃ³ porque vocÃª nÃ£o tem um PlayStation VR para jogar Batman: Arkham VR. A Warner Bros. Acaba de anunciar que o game vai chegar tambÃ©m aos PCs â€“ mais especificamente, para HTC Vive e Oculus Rift â€“ no dia 25 de abril.\r\n\r\nO anÃºncio veio junto de um trailer trazido no canal oficial do game no YouTube. Nele, nÃ£o apenas temos a chance de ver mais da jogatina que o espera no tÃ­tulo, indo do uso dos gadgets Ã  impressionante cena de Bruce vestindo o traje do Homem-Morcego, como tambÃ©m vemos isso alternando com cenas de gamers usando ambos os acessÃ³rios VR de PC. O resultado Ã© bem impressionante.\r\n\r\nÃ‰ claro que, no final das contas, isso ainda nÃ£o aumenta em tanto assim o nÃºmero de pessoas que vÃ£o ter acesso ao game (afinal, ambos os aparelhos possuem preÃ§os bastante salgados para boa parte dos gamers do paÃ­s), mas todo crescimento no suporte de um tÃ­tulo como esses Ã© algo muitÃ­ssimo bem-vindo.', 'ca3fc2a84c612baba1fb62e756d5516f.jpg', '2017-04-03 19:21:17', 'PAULO GUILHERME'),
(30, '\\''ConteÃºdo Adulto\\'' chega Ã  Netflix com dicas valiosas no \\''1Âº de abril\\''', 'Netflix divulgou nesta sexta-feira (31) a sÃ©rie original â€œConteÃºdo Adultoâ€, destinada apenas para maiores de 18 anos â€” e tambÃ©m para quem mente a idade na internet (nota do editor: nÃ£o encorajamos). Quem clica no link divulgado pela empresa no Facebook, entretanto, pode se surpreender com os episÃ³dios â€œAlta voltagemâ€ e â€œNoite de entregaâ€.\r\n\r\nNo primeiro, uma mulher de camisola recebe o eletricista para consertar a resistÃªncia no chuveiro. JÃ¡ em â€œNoite de entregaâ€, um homem e uma mulher sÃ£o os Ãºnicos dentro uma empresa Ã  noite. Dois clichÃªs jÃ¡ vistos em muitas coletÃ¢neas de clichÃªs? Mais do que isso... ', '4c57adba2fa6c08631f5a6d969c10f7b.jpg', '2017-04-03 19:23:49', 'MARIANA MARQUES'),
(31, 'Android passa Windows e se torna o sistema operacional mais usado do mundo', 'Android Nougat Ã© o nome do novo sistema operacional do Google. (Foto: DivulgaÃ§Ã£o/Google)\r\n\r\nO Android, do Google, passou o Windows e se tornou o sistema operacional mais usado do mundo em marÃ§o de 2017, informou a StatCounter em relatÃ³rio divulgado nesta segunda-feira (3). Ã‰ a primeira vez desde que foi lanÃ§ado na dÃ©cada de 1980 que o topo nÃ£o Ã© ocupado pelo software da Microsoft.\r\n\r\nO levantamento da firma de anÃ¡lise considera computadores, notebooks, tablets e smartphones. O Android estava em 37,93% dos aparelhos, enquanto o Windows equipava 37,91% deles.\r\n\r\nâ€œEsse Ã© um marco histÃ³rico na histÃ³ria da tecnologia e o fim de uma eraâ€, comentou, em nota, Aodhan Cullen, presidente-executivo da StatCounter.\r\nâ€œMarca o fim da lideranÃ§a da Microsoft em todo o mundo do mercado de sistemas operacionais que jÃ¡ dura desde de os anos 1980. TambÃ©m representa uma maior ruptura par ao Android, que tinha apenas 2,4% do uso de internet no mundo hÃ¡ cinco anos.â€ A tÃ­tulo de comparaÃ§Ã£o, em marÃ§o de 2012, o Windows era o sistema operacional de quatro a cada cinco dispositivos analisados.\r\n\r\nA danÃ§a das cadeiras ocorre devido ao avanÃ§o do smartphone, que se tornou o aparelho conectado mais usado para acessar a internet. Tanto Ã© que o Windows ainda Ã© o sistema operacional de 84% dos computadores e notebooks.\r\n\r\nA predileÃ§Ã£o dos asiÃ¡ticos pelo Android tambÃ©m ajudou. Na Ãsia, o sistema do Google estÃ¡ em 52,2% dos aparelhos, enquanto a fatia do Windows Ã© de 29,2%. \r\n\r\nNa AmÃ©rica do Norte e Europa, no entanto, o principal serviÃ§o da Microsoft ainda Ã© o mais usado. Na regiÃ£o formada por Estados Unidos, CanadÃ¡ e MÃ©xico, a presenÃ§a do iOS, da Apple, ainda Ã© maior que a do Android.', 'f25f0fe08ffbd788cc0f13deee331ea3.jpg', '2017-04-03 19:26:14', 'G1'),
(32, 'RelÃ³gio do Windows estÃ¡ instÃ¡vel e deixa servidores vulnerÃ¡veis a ataques', 'Como o seu relÃ³gio do Windows estÃ¡ sempre com a hora certa? Bem mais fÃ¡cil de explicar e sem nenhum tipo de magia, a resposta Ã© simples: existe um serviÃ§o (Windows Time Service) do sistema que se conecta com um servidor e retorna com o horÃ¡rio real. Contudo, esse recurso estÃ¡ atualmente com inconsistÃªncia e gerando vÃ¡rios problemas no mundo todo.\r\n\r\nVocÃª pode achar que uma hora errada nÃ£o Ã© nada demais, mas nÃ£o Ã© bem assim. Quando pensamos no lado â€œservidorâ€ da computaÃ§Ã£o, muitas operaÃ§Ãµes, sites e mecanismos dependem do horÃ¡rio preciso. O problema Ã© tÃ£o sÃ©rio que pode se tornar um grande exploit para ataques externos, prejudicando a seguranÃ§a de muitos data centers.\r\n\r\n\\"Os horÃ¡rios incompatÃ­veis podem gerar inconsistÃªncias e, dessa forma, criando erros e brechas de seguranÃ§a\\"\r\n\r\nA anomalia do serviÃ§o â€œtime.windows.comâ€ ainda nÃ£o foi comentada pela Microsoft, mas diversos usuÃ¡rios estÃ£o reportando os empecilhos no Reddit e Twitter, relatando que a operaÃ§Ã£o de data e horÃ¡rio do Windows estÃ¡ tÃ£o ruim que em alguns casos o sistema reporta minutos com 61 segundos, uma hora adiantada Ã  real ou atÃ© mesmo fusos horÃ¡rios errados.', '031a8d768062a499e2c71d72b1151da3.jpg', '2017-04-03 19:30:59', 'VINICIUS MUNHOZ'),
(33, 'PokÃ©mon GO ajuda a zerar suicÃ­dios em local conhecido por mortes no JapÃ£o', 'Ã‰ verdade que PokÃ©mon GO perdeu uma grande parcela de jogadores pelos mais diversos motivos desde que foi lanÃ§ado, mas os remanescentes tem feito muito mais do que sÃ³ continuado a capturar criaturas virtuais com realidade aumentada. No JapÃ£o, o game tem ajudado atÃ© a prevenir mortes.\r\n\r\nSegundo o site Rocket News, a presenÃ§a constante de jogadores na cadeia de penhascos de Tojinbo impediu atÃ© agora o registro de qualquer suicÃ­dio da regiÃ£o â€” e o local Ã© um dos vÃ¡rios pontos do paÃ­s escolhidos para esse propÃ³sito por japoneses.\r\n\r\nAlÃ©m de um ponto turÃ­stico famoso, Tojinbo registrou 16 mortes em 2016. AtÃ© agora, em 2017, nenhuma aconteceu. E quem garante isso Ã© o chefe da patrulha voluntÃ¡ria de prevenÃ§Ã£o contra suicÃ­dios do local, Yukio Shige. De acordo com ele, a taxa jÃ¡ havia diminuÃ­do quando o jogo saiu, mas sÃ³ agora foi possÃ­vel notar que a ligaÃ§Ã£o com PokÃ©mon GO nÃ£o Ã© sÃ³ coincidÃªncia.', '1bcc6479caf363203565d6e2c26984ef.jpg', '2017-04-03 19:32:33', 'NILTON KLEINA'),
(34, 'Final Fantasy XV: A New Empire Ã© lanÃ§ado para Android e iOS', 'Depois de uma boa rodada de rumores, o game Final Fantasy XV: A New Empire finalmente foi lanÃ§ado para Android e iOS. O tÃ­tulo jÃ¡ estÃ¡ disponÃ­vel nas lojas dos dois sistemas operacionais, mas vocÃª sÃ³ pode fazer o download caso more na Nova ZelÃ¢ndia. Isso quer dizer que o lanÃ§amento da plataforma foi feito de forma bem limitada, e, infelizmente, nÃ£o temos informaÃ§Ãµes sobre quando o game serÃ¡ liberado no Brasil.\r\n\r\nSeja como for, o tÃ­tulo Ã© uma mistura de MMO, com RTS e City Builder e, de acordo com a descriÃ§Ã£o na Google Play, vocÃª terÃ¡ a oportunidade de ter herÃ³is jÃ¡ conhecidos do Final Fantasy XV para PS4, como Noctis, Gladiolus, Ignis, Prompto, Cindy e outros, no seu time no mobile.', '346f2fba0a94f43a6aa82097960f23a9.jpg', '2017-04-03 19:34:17', 'LEONARDO MÃœLLER'),
(35, '11 anos de trabalho: sonda da NASA completa 50 mil voltas ao redor de Marte', ' HÃ¡ 11 anos analisando o Planeta Vermelho, a sonda Mars Reconnaissance Orbiter (MRO) acaba de bater uma marca bastante impressionante e que mostra o quanto estamos interessados pelo nosso vizinho no sistema solar. Afinal, o equipamento completou nada menos que 50 mil Ã³rbitas em torno de Marte e superou qualquer expectativa em cima de sua longevidade na missÃ£o espacial.\r\n\r\nSaindo da Terra a bordo do foguete Atlas V, em 2005, a MRO demorou cerca de um ano para finalmente chegar nas proximidades de Marte. Uma vez lÃ¡, o brinquedinho da NASA comeÃ§ou a se posicionar para viajar ao redor do planeta colhendo o maior nÃºmero de imagens possÃ­veis da sua geografia. A agÃªncia espacial norte-americana sabia que essa seria uma tarefa bem longa, mas nÃ£o imaginava que a sonda, sozinha, seria capaz de se manter mais de uma dÃ©cada no batente.', 'ec17f57ce2e6bce649968362fbf26085.jpg', '2017-04-03 19:36:05', 'MARCELO RODRIGUES'),
(37, 'Netflix: agora dÃ¡ para baixar filmes ou sÃ©ries e ver offline no Windows 10', 'A Netflix finalmente trouxe ao Windows uma das novidades mais pedidas pela comunidade a respeito do serviÃ§o de streaming. A partir de agora, quem tem o aplicativo gratuito para Windows 10 (deskop e notebooks) ou Windows 10 Mobile pode fazer o download de uma sÃ©rie de filmes ou sÃ©ries para assistir ao conteÃºdo quando estiver offline.\r\n\r\nVale lembrar que isso sÃ³ Ã© possÃ­vel pelo aplicativo baixado na Windows Store â€” ou seja, nÃ£o funciona pelo site visitado pelo navegador. O funcionamento Ã© igual ao processo no mobile: vocÃª seleciona o episÃ³dio de sÃ©rie ou longa-metragem que deseja baixar, aguarda o download ser concluÃ­do e acessa o conteÃºdo a qualquer momento em uma nova aba especial.\r\n\r\nNem todos os filmes e sÃ©ries da Netflix estÃ£o disponÃ­veis para download, mas o catÃ¡logo Ã© grande e bem variado. NÃ£o sÃ£o todas as produÃ§Ãµes originais da Netflix, por exemplo, mas as opÃ§Ãµes ainda sÃ£o diversas. A alternativa Ã© boa para quem vai viajar para um local sem conexÃ£o ou quer se prevenir para quando ficar sem internet. Relembre: Netflix agora deixa vocÃª baixar filmes e sÃ©ries para ver offline ', '96c9a4d8e51def152a227ffd71188eb4.jpg', '2017-04-03 19:40:37', 'NILTON KLEINA'),
(38, 'As novidades da semana na Netflix (12/08/2016)', 'Ã‰ difÃ­cil achar alguÃ©m que nÃ£o ame a Netflix e as inÃºmeras opÃ§Ãµes disponÃ­veis em seu catÃ¡logo. Por isso, sempre que uma lista de novidades aparece no serviÃ§o, muitos consumidores ficam ansiosos para saber o que vem por aÃ­. Em agosto, os servidores da Netflix estÃ£o sendo atualizados com alguns tÃ­tulos bem legais e que podem ser Ã³timas opÃ§Ãµes para o final de semana.\r\n\r\nEntre os principais tÃ­tulos adicionados, podemos destacar a chegada de \\"O Hobbit: A Batalha dos Cinco ExÃ©rcitos\\" e tambÃ©m da sÃ©rie original \\"The Get Down\\". VocÃª nÃ£o vai perder, nÃ£o Ã© mesmo? Confira abaixo todos os novos filmes e as sÃ©ries que entraram no serviÃ§o durante esta semana.\r\n\r\nPrincipais destaques\r\nO Hobbit: A Batalha dos Cinco ExÃ©rcitos\r\nThe Get Down', 'b92ee2554e914fe869ea9f93f43f8de6.jpg', '2017-04-03 19:43:04', 'RENAN HAMANN'),
(39, 'Apple encomenda mais de 70 milhÃµes de telas OLED da Samsung', 'Os rumores estavam certos: a Apple realmente vai incluir telas OLED nos prÃ³ximos iPhones. Anteriormente, a indicaÃ§Ã£o era que a MaÃ§Ã£ colocaria painÃ©is OLED no iPhone 8, enquanto a linha iPhone 7s e iPhone 7s Plus continuaria com a LCD. PorÃ©m, a Apple acabou de encomendar 70 milhÃµes de painÃ©is OLED para a Samsung, e isso pode indicar que todos os aparelhos podem chegar com essa tecnologia.\r\n\r\nA Samsung Ã© a Ãºnica fornecedora de telas para a Apple\r\nSegundo a Nikkei, a Samsung continuarÃ¡ sendo a Ãºnica fornecedora de telas para a Apple. Exatamente: caso vocÃª nÃ£o saiba, a principal concorrente da Apple Ã© tambÃ©m a Ãºnica fornecedora de painÃ©is para iPhones.\r\n\r\nÃ‰ esperado que o iPhone 8 chegue ao mercado com uma tela de ponta a ponta â€” similar ao LG G6 e Samsung Galaxy S8 â€”, com corpo de vidro e dentro de uma faixa de preÃ§o bem salgada, girando em torno de US$ 1 mil.', '147f8b61202cf9ed33fa3099a90dd642.jpg', '2017-04-03 19:44:44', 'FELIPE PAYÃƒO '),
(40, 'Executivos de Wall Street utilizam WhatsApp para realizar trapaÃ§as', 'A encriptaÃ§Ã£o de ponta a ponta do WhatsApp Ã© Ã³tima para a nossa privacidade, porÃ©m, tambÃ©m Ã© utilizada para fins ilegais. Neste caso, executivos de Wall Street, sÃ­mbolo do mercado de negÃ³cios, estÃ£o utilizando mensageiros seguros para trapacear, como o prÃ³prio WhatsApp e o Signal, que foi recomendado pelo delator Edward Snowden.\r\n\r\nMensagens dÃºbias e dicas ilegais de mercado sempre foram comuns em mercados como os fundos hedge â€” fundos de cobertura de alto risco e com muita especulaÃ§Ã£o. Por exemplo, na semana passada, um banqueiro do Jefferies Group foi condenado no Reino Unido por compartilhar informaÃ§Ãµes confidenciais no WhatsApp. A multa? 43,5 mil euros, cerca de R$ 143 mil.\r\n\r\nDois executivos de fundo hedge foram pegos se comunicando ilegalmente via WhatsApp\r\nComo nota a Bloomberg, desde comerciantes atÃ© banqueiros e gerentes estÃ£o \\"abraÃ§ando estes aplicativos\\" mais seguros. Isso porque, por meio deles, aÃ§Ãµes ilegais nÃ£o podem ser rastreadas. \\"NÃ³s temos visto em nossas investigaÃ§Ãµes que um padrÃ£o estÃ¡ movendo para todos, e as mudanÃ§as da tecnologias estÃ£o causando grande parte disso\\", comentou o advogado William McGovern, da Kobre & Kim.', '4b6eb7f15998da507e26e1a466b44e7c.jpg', '2017-04-03 19:46:41', 'FELIPE PAYÃƒO '),
(42, 'Pesquisa revela qual Ã© a melhor internet banda larga em cada estado do Brasil', 'A AgÃªncia Nacional de TelecomunicaÃ§Ãµes (Anatel) realizou recentemente uma pesquisa de satisfaÃ§Ã£o com mais de 150 mil pessoas espalhadas pelo Brasil. O objetivo do estudo foi descobrir o que os clientes de internet banda larga fixa acham dos serviÃ§os oferecidos por suas provedoras.\r\n\r\nCom base nessa pesquisa, o site Melhor Plano divulgou nesta segunda-feira, 3, um levantamento que mostra qual Ã© a melhor operadora em cada estado do Brasil, de acordo com a avaliaÃ§Ã£o dos prÃ³prios consumidores. Confira o ranking logo abaixo.\r\n\r\nAcre (AC): NET\r\n\r\nAlagoas (AL): Vivo\r\n\r\nAmazonas (AM): NET\r\n\r\nBahia (BA): NET\r\n\r\nCearÃ¡ (CE): NET\r\n\r\nDistrito Federal (DF): NET\r\n\r\nEspÃ­rito Santo (ES): NET\r\n\r\nGoiÃ¡s (GO): Vivo\r\n\r\nMaranhÃ£o (MA): NET\r\n\r\nMato Grosso (MT): NET\r\n\r\nMato Grosso do Sul (MS): NET\r\n\r\nMinas Gerais (MG): Algar Telecom\r\n\r\nParÃ¡ (PA): NET\r\n\r\nParaÃ­ba (PB): NET\r\n\r\nParanÃ¡ (PR): Sercomtel\r\n\r\nPernambuco (PE): NET\r\n\r\nPiauÃ­ (PI): NET\r\n\r\nRio de Janeiro (RJ): Tim\r\n\r\nRio Grande do Norte (RN): Cabo Telecom\r\n\r\nRio Grande do Sul (RS): NET\r\n\r\nRondÃ´nia (RO): Blue\r\n\r\nRoraima (RR): Oi\r\n\r\nSanta Catarina (SC): Vivo\r\n\r\nSÃ£o Paulo (SP): Tim\r\n\r\nSergipe (SE): NET\r\n\r\nTocantins (TO): NET\r\n\r\nPara montar a lista, o Melhor Plano usou dados da Anatel sobre a satisfaÃ§Ã£o dos clientes em relaÃ§Ã£o Ã s suas operadoras contratadas. Quatro critÃ©rios primordiais foram avaliados pelos consumidores: velocidade da internet, estabilidade da conexÃ£o, disponibilidade da rede e o atendimento da empresa.\r\n\r\nDesse modo, algumas operadoras podem se destacar em um ou mais critÃ©rios, ou em todos. O levantamento do Melhor Plano entÃ£o selecionou como \\"melhor operadora\\" aquela que foi mais bem avaliada em um maior nÃºmero de critÃ©rios. Apenas o AmapÃ¡ ficou de fora da pesquisa, jÃ¡ que nenhuma operadora do estado foi avaliada pela Anatel.\r\n\r\nO Melhor Plano Ã© o mesmo que divulgou, em marÃ§o, um outro levantamento sobre o preÃ§o mÃ©dio da internet banda larga mÃ³vel no Brasil. Comparando tarifas com velocidade e limite de franquia, o site revelou qual Ã© a internet mÃ³vel mais cara e qual Ã© a mais barata no paÃ­s. ', '49d88545030e6f56581ba70f5bbe4170.jpg', '2017-04-03 19:53:03', 'LUCAS CARVALHO'),
(45, 'Testamos: bom desempenho nÃ£o justifica defeitos do Moto G5 Plus', 'Em apenas cinco anos de vida, o Moto G jÃ¡ passou pelas mÃ£os de pelo menos trÃªs empresas diferentes. Em primeiro lugar, a Motorola, que Ã© dona da marca e continua assim atÃ© hoje. Em segundo lugar pela dona da Motorola, que de 2013 a 2014 foi o Google e que desde 2015 Ã© a Lenovo.\r\n\r\nÃ‰ difÃ­cil saber como essas mudanÃ§as afetam o desenvolvimento do produto final, especialmente porque os ciclos de produÃ§Ã£o de smartphones levam de dois a trÃªs anos para serem concluÃ­dos. Mas Ã© nÃ­tido o quanto o Moto G mudou desde sua primeira geraÃ§Ã£o atÃ© hoje.\r\n\r\nEm marÃ§o deste ano, a Motorola lanÃ§ou o Moto G5, quinta geraÃ§Ã£o de seu smartphone mais popular. Se no ano passado a empresa apostou numa famÃ­lia com trÃªs dispositivos diferentes, neste ano ela foi bem mais econÃ´mica: apenas duas versÃµes, o Moto G5 e o Moto G5 Plus.', 'cc9fb4a81a366cd868e388de8764af98.jpg', '2017-04-03 20:00:19', 'LUCAS CARVALHO');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `noticia`
--
ALTER TABLE `noticia`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `noticia`
--
ALTER TABLE `noticia`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=47;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
